# Train: Training hyperparameters.
Train:
  # Directory where checkpoints and logs will be saved (subdirectories will be created per frequency band)
  model_dir: "./models"
  # Number of GPUs to use (0 for CPU-only)
  n_gpus: 0
  # Path to checkpoint file if resuming training (leave empty to train from scratch)
  ckpt_file: ""
  # Number of training epochs
  n_epoch: 5
  # Learning rate for the optimizer
  lr: 0.001
  # Weight factor for the KL divergence term
  beta: 1.0
  # Frequency (in steps) at which to log training info
  n_print: 100

# Model: Model architecture parameters.
Model:
  # Number of input channels (for single-channel EEG)
  in_channels: 1
  # Negative slope for LeakyReLU activations
  negative_slope: 0.2
  # Whether the decoder uses a final LSTM layer (set to false if not desired)
  decoder_last_lstm: false

# Dataset: Parameters for the dataset.
DataSet: 
  # Path to the directory containing the EEG clips
  data_dir: "./new_data/train"
  # Length of the EEG clips
  clip_len: 256
  # Batch size for trainings
  batch_size: 64

  
  
  
