# Test: Re-use many of the same paths/params as training
Train:
  # Base directory where the per-band model checkpoints live
  model_dir: "/u/noka/VAEEG/models"
  # Number of training epochs (so we know which ckpt to load)
  n_epoch: 100
  # Number of GPUs to use (0 for CPU-only)
  n_gpus: 4

# Model: same architecture specs as for training
Model:
  in_channels: 1
  negative_slope: 0.2
  decoder_last_lstm: false
  # Whether to use deterministic mode (no variance in latent sampling)
  deterministic: true

# DataSet: point to your test split
DataSet:
  # Base folder containing per-band subdirs; expect e.g. ".../test/theta/*.npy"
  data_dir: "/ptmp/noka/new_data/tusz2/test"
  # Clip length (must match how you trained)
  clip_len: 256
  # Batch size for evaluation (can be big since no gradients)
  batch_size: 16384
  # DataLoader workers
  num_workers: 1